#!/usr/bin/php
<?php

use Lab03\Stream\CompressOutputStream;
use Lab03\Stream\DecompressInputStream;
use Lab03\Stream\DecryptInputStream;
use Lab03\Stream\EncryptOutputStream;
use Lab03\Stream\FileInputStream;
use Lab03\Stream\FileOutputStream;
use Lab03\Stream\Option;

require_once(__DIR__ . '/../../vendor/autoload.php');

system("clear");
echo "\e[4m"; // <underline>
if ($argc < 3) {
    echo "Ошибка параметров \n";
    exit;
}

$outputFilePath = __DIR__ . DIRECTORY_SEPARATOR . array_pop($argv);
$inputFilePath = __DIR__ . DIRECTORY_SEPARATOR . array_pop($argv);

$inputStream = new FileInputStream($inputFilePath);
$outputStream = new FileOutputStream($outputFilePath);

for ($i = 1; $i < $argc - 2;) {
    switch ($argv[$i]) {
        case Option::ENCRYPT:
            $i++;
            $outputStream = new EncryptOutputStream($outputStream, getParameterOrException($argv, $i));
            break;
        case Option::DECRYPT:
            $i++;
            $inputStream = new DecryptInputStream($inputStream, getParameterOrException($argv, $i));
            break;
        case Option::COMPRESS:
            $i++;
            $outputStream = new CompressOutputStream($outputStream);
            break;
        case Option::DECOMPRESS:
            $i++;
            $inputStream = new DecompressInputStream($inputStream);
            break;

        default:
            echo "Ошибка параметров \n";
            break;
    }
    $i++;
}

while (!$inputStream->isEof()) {
    $data = $inputStream->readByte();
    $outputStream->writeBlock($data, strlen($data));
}

function getParameterOrException(array $argv, int $i)
{
    if (!isset($argv[$i])) {
        throw new RuntimeException('не указан параметр для опции --encrypt' . Option::ENCRYPT);
    }
    return $argv[$i];
}

echo "Выполнено\n";